# Generated by Django 5.1.3 on 2024-12-26 21:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPost', '0002_rename_descripcion_post_texto_post_tit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2024, 12, 26, 18, 42, 12, 88210)),
        ),
    ]
