# Generated by Django 5.1.3 on 2025-01-04 19:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPost', '0005_alter_post_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tit',
            new_name='titulo',
        ),
        migrations.AddField(
            model_name='post',
            name='epigrafe',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='img-posts'),
            preserve_default=False,
        ),
    ]
