# Generated by Django 5.1.3 on 2025-01-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPost', '0006_rename_tit_post_titulo_post_epigrafe_post_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='epigrafe',
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.CharField(max_length=20),
        ),
    ]
