# Generated by Django 5.1.3 on 2025-01-04 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appPost', '0007_remove_post_epigrafe_alter_post_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img-posts'),
        ),
    ]
