# Generated by Django 5.1.3 on 2024-12-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=30)),
                ('gmail', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=15)),
                ('fecha_nacimiento', models.DateField()),
                ('descripcion', models.CharField(max_length=150)),
            ],
        ),
    ]
