# Generated by Django 5.1.3 on 2024-12-26 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
