# Generated by Django 5.1.3 on 2025-01-02 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appuser', '0005_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(default='avatares/default-pfp.png', upload_to='avatares'),
        ),
    ]
